# Generated by Django 5.0.4 on 2024-04-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0002_veiculo_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='imagem',
        ),
    ]
