# Generated by Django 5.0.3 on 2024-04-01 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0003_alter_cor_options_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='marca',
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='garagem.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcas', to='garagem.marca')),
            ],
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='garagem.modelo'),
        ),
    ]
