# Generated by Django 5.0.3 on 2024-04-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0004_remove_veiculo_marca_modelo_veiculo_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(max_length=100),
        ),
    ]
