# Generated by Django 5.0.3 on 2024-04-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0007_alter_veiculo_cor_alter_veiculo_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='acessorio',
            field=models.ManyToManyField(to='garagem.acessorio'),
        ),
    ]
