# Generated by Django 5.0.3 on 2024-04-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0008_veiculo_acessorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='acessorio',
            field=models.ManyToManyField(related_name='veiculos', to='garagem.acessorio'),
        ),
    ]
